version: "3.9"

services:
  web:
    build:
      context: .
      args:
        ENV: dev
    volumes:
      - .:/code
    ports:
      - "5150:5000" # flask dev server
    environment:
      - FLASK_APP=/code/src/main.py
      - DATABASE_URL=postgresql+psycopg2://postgres:foobar@psql/eda
      - PYTHONPATH=/code/src/foodie2ue
    command: flask run -h 0.0.0.0 -p 5000
    depends_on:
      - psql

  psql:
    image: postgres:12-alpine
    environment:
      - POSTGRES_PASSWORD=foobar
      - POSTGRES_DB=eda
    ports:
      - "8001:5432"
