version: "3.9"

services:
  web:
    build:
      context: .
      args:
        ENV: dev
    volumes:
      - .:/code
    ports:
      - "5150:5000" # flask dev server
    env_file:
      - envs/dev.env
      - envs/secret.env
    command: flask run -h 0.0.0.0 -p 5000
    depends_on:
      - psql

  psql:
    image: postgres:12-alpine
    env_file:
      - envs/dev.env
    ports:
      - "8001:5432"
