"""empty message

Revision ID: 34cc88471c2a
Revises:
Create Date: 2022-06-11 05:56:44.444822

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '34cc88471c2a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'menuitems',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
        sa.Column('updated', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
        sa.Column('name', sa.String(length=64), nullable=True),
        sa.Column('description', sa.String(length=256), nullable=True),
        sa.Column('size', sa.String(length=32), nullable=True),
        sa.Column('price', sa.Numeric(precision=4, scale=2), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menuitems')
    # ### end Alembic commands ###
