"""empty message

Revision ID: 536f34b85aa9
Revises: 696eeb942577
Create Date: 2022-07-07 22:27:45.990753

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '536f34b85aa9'
down_revision = '696eeb942577'
branch_labels = None
depends_on = None


def upgrade() -> None:

    order_status = postgresql.ENUM(
        'NEW',
        'PREPARING',
        'READY_FOR_PICKUP',
        'ENROUTE',
        'DELIVERED',
        name='order_status_enum',
    )
    order_status.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('menuitems', 'name', existing_type=sa.VARCHAR(length=64), nullable=False)
    op.alter_column('menuitems', 'size', existing_type=sa.VARCHAR(length=32), nullable=False)
    op.drop_constraint('menuitems_name_key', 'menuitems', type_='unique')
    op.add_column('orders', sa.Column('eta', sa.DateTime(), nullable=True))
    op.add_column(
        'orders',
        sa.Column('status',
                  sa.Enum('NEW',
                          'PREPARING',
                          'READY_FOR_PICKUP',
                          'ENROUTE',
                          'DELIVERED',
                          name='order_status_enum'),
                  nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'status')
    op.drop_column('orders', 'eta')
    op.create_unique_constraint('menuitems_name_key', 'menuitems', ['name'])
    op.alter_column('menuitems', 'size', existing_type=sa.VARCHAR(length=32), nullable=True)
    op.alter_column('menuitems', 'name', existing_type=sa.VARCHAR(length=64), nullable=True)
    # ### end Alembic commands ###

    order_status = postgresql.ENUM(
        'NEW',
        'PREPARING',
        'READY_FOR_PICKUP',
        'ENROUTE',
        'DELIVERED',
        name='order_status_enum',
    )
    order_status.drop(op.get_bind())
