"""empty message

Revision ID: 57b41197d3bd
Revises:
Create Date: 2022-06-17 18:40:14.812661

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '57b41197d3bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'addons',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
        sa.Column('updated', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
        sa.Column('name', sa.String(length=64), nullable=True),
        sa.Column('description', sa.String(length=256), nullable=True),
        sa.Column('price', sa.Numeric(precision=4, scale=2), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'))
    op.create_table(
        'drivers',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
        sa.Column('updated', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
        sa.Column('first_name', sa.String(length=64), nullable=False),
        sa.Column('last_name', sa.String(length=64), nullable=False),
        sa.Column('phone_number', sa.String(length=16), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('phone_number'))
    op.create_table(
        'menuitems',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
        sa.Column('updated', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
        sa.Column('name', sa.String(length=64), nullable=True),
        sa.Column('description', sa.String(length=256), nullable=True),
        sa.Column('size', sa.String(length=32), nullable=True),
        sa.Column('price', sa.Numeric(precision=4, scale=2), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'))
    op.create_index('unique_name_and_size', 'menuitems', ['name', 'size'], unique=True)
    op.create_table('menuitem_addons',
                    sa.Column('menuitem_id', sa.Integer(), nullable=False),
                    sa.Column('addon_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['addon_id'],
                        ['addons.id'],
                    ),
                    sa.ForeignKeyConstraint(
                        ['menuitem_id'],
                        ['menuitems.id'],
                    ),
                    sa.PrimaryKeyConstraint('menuitem_id', 'addon_id'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menuitem_addons')
    op.drop_index('unique_name_and_size', table_name='menuitems')
    op.drop_table('menuitems')
    op.drop_table('drivers')
    op.drop_table('addons')
    # ### end Alembic commands ###
