"""empty message

Revision ID: 696eeb942577
Revises: 57b41197d3bd
Create Date: 2022-07-07 04:45:51.863860

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '696eeb942577'
down_revision = '57b41197d3bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('customer_first_name', sa.String(length=64), nullable=False),
    sa.Column('customer_last_name', sa.String(length=64), nullable=False),
    sa.Column('customer_phone_number', sa.String(length=16), nullable=False),
    sa.Column('customer_email', sa.String(length=32), nullable=False),
    sa.Column('customer_address', sa.String(length=64), nullable=False),
    sa.Column('customer_city', sa.String(length=64), nullable=False),
    sa.Column('customer_state', sa.String(length=16), nullable=False),
    sa.Column('customer_zip', sa.String(length=16), nullable=False),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tax', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('delivery_fee', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    # ### end Alembic commands ###
