"""empty message

Revision ID: afddff1ff975
Revises:
Create Date: 2022-06-11 22:02:28.153686

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'afddff1ff975'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'menuitems',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
        sa.Column('updated', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
        sa.Column('name', sa.String(length=64), nullable=True),
        sa.Column('description', sa.String(length=256), nullable=True),
        sa.Column('size', sa.String(length=32), nullable=True),
        sa.Column('price', sa.Numeric(precision=4, scale=2), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'))
    op.create_index('unique_name_and_size', 'menuitems', ['name', 'size'], unique=True)
    op.create_table(
        'addons',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
        sa.Column('updated', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
        sa.Column('name', sa.String(length=64), nullable=True),
        sa.Column('description', sa.String(length=256), nullable=True),
        sa.Column('price', sa.Numeric(precision=4, scale=2), nullable=False),
        sa.Column('menuitem_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ['menuitem_id'],
            ['menuitems.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('addons')
    op.drop_index('unique_name_and_size', table_name='menuitems')
    op.drop_table('menuitems')
    # ### end Alembic commands ###
