"""empty message

Revision ID: c836c5a0a4ad
Revises: 34cc88471c2a
Create Date: 2022-06-11 06:00:32.303606

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c836c5a0a4ad'
down_revision = '34cc88471c2a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'menuitem_addons',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
        sa.Column('updated', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
        sa.Column('name', sa.String(length=64), nullable=True),
        sa.Column('description', sa.String(length=256), nullable=True),
        sa.Column('price', sa.Numeric(precision=4, scale=2), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menuitem_addons')
    # ### end Alembic commands ###
