"""empty message

Revision ID: cda2a736ecc1
Revises: 536f34b85aa9
Create Date: 2022-07-15 04:09:05.056633

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cda2a736ecc1'
down_revision = '536f34b85aa9'
branch_labels = None
depends_on = None

DRIVER_STATUS_AVAILABLE = 'AVAILABLE'
DRIVER_STATUS_ENROUTE = 'ENROUTE'
DRIVER_STATUS_UNAVAILABLE = 'UNAVAILABLE'
DRIVER_STATUSES = (
    DRIVER_STATUS_AVAILABLE,
    DRIVER_STATUS_ENROUTE,
    DRIVER_STATUS_UNAVAILABLE,
)

DELIVERY_STATUS_NEW = 'NEW'
DELIVERY_STATUS_ENROUTE = 'ENROUTE'
DELIVERY_STATUS_CANCELED = 'CANCELED'
DELIVERY_STATUS_DELIVERED = 'DELIVERED'
DELIVERY_STATUSES = (
    DELIVERY_STATUS_NEW,
    DELIVERY_STATUS_ENROUTE,
    DELIVERY_STATUS_CANCELED,
    DELIVERY_STATUS_DELIVERED,
)


def upgrade() -> None:

    driver_status = postgresql.ENUM(*DRIVER_STATUSES, name='driver_status_enum')
    driver_status.create(op.get_bind())

    # I'm not sure why this one didn't need to be created explicity. Somehow the ENUM is being
    # created during table creation, which is not the same behavior observed with the
    # driver_status_enum or the enum in migration 536f34b85aa9.py
    #
    # Note we *do* need to delete it in the downgrade.
    #
    # delivery_status = postgresql.ENUM(*DELIVERY_STATUSES, name='delivery_status_enum')
    # delivery_status.create(op.get_bind())

    # # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'delivery_events',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('order_id', sa.Integer(), nullable=False),
        sa.Column('driver_id', sa.Integer(), nullable=False),
        sa.Column('created', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
        sa.Column('updated', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
        sa.Column('status',
                  sa.Enum(*DELIVERY_STATUSES, name='delivery_status_enum'),
                  nullable=False),
        sa.ForeignKeyConstraint(
            ['driver_id'],
            ['drivers.id'],
        ),
        sa.ForeignKeyConstraint(
            ['order_id'],
            ['orders.id'],
        ),
        sa.PrimaryKeyConstraint('id'))
    op.add_column(
        'drivers',
        sa.Column('status', sa.Enum(*DRIVER_STATUSES, name='driver_status_enum'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drivers', 'status')
    op.drop_table('delivery_events')

    # # ### end Alembic commands ###

    driver_status = postgresql.ENUM(*DRIVER_STATUSES, name='driver_status_enum')
    driver_status.drop(op.get_bind())

    delivery_status = postgresql.ENUM(*DELIVERY_STATUSES, name='delivery_status_enum')
    delivery_status.drop(op.get_bind())
