"""empty message

Revision ID: 589653818028
Revises: 
Create Date: 2022-06-10 04:36:56.833767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '589653818028'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('size', sa.String(length=32), nullable=True),
    sa.Column('price', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('unique_name_and_size', 'menu_items', ['name', 'size'], unique=True)
    op.create_table('add_ons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('menuitem', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('price', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['menuitem'], ['menu_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('add_ons')
    op.drop_index('unique_name_and_size', table_name='menu_items')
    op.drop_table('menu_items')
    # ### end Alembic commands ###
