ORDER_STATUS_NEW = 'NEW'
ORDER_STATUS_PREPARING = 'PREPARING'
ORDER_STATUS_READY_FOR_PICKUP = 'READY_FOR_PICKUP'
ORDER_STATUS_ENROUTE = 'ENROUTE'
ORDER_STATUS_DELIVERED = 'DELIVERED'

ORDER_STATUSES = (
    ORDER_STATUS_NEW,
    ORDER_STATUS_PREPARING,
    ORDER_STATUS_READY_FOR_PICKUP,
    ORDER_STATUS_ENROUTE,
    ORDER_STATUS_DELIVERED,
)
