ORDER_STATUS_NEW = 'NEW'
ORDER_STATUS_PREPARING = 'PREPARING'
ORDER_STATUS_READY_FOR_PICKUP = 'READY_FOR_PICKUP'
ORDER_STATUS_ENROUTE = 'ENROUTE'
ORDER_STATUS_DELIVERED = 'DELIVERED'

ORDER_STATUSES = (
    ORDER_STATUS_NEW,
    ORDER_STATUS_PREPARING,
    ORDER_STATUS_READY_FOR_PICKUP,
    ORDER_STATUS_ENROUTE,
    ORDER_STATUS_DELIVERED,
)

DRIVER_STATUS_AVAILABLE = 'AVAILABLE'
DRIVER_STATUS_ENROUTE = 'ENROUTE'
DRIVER_STATUS_UNAVAILABLE = 'UNAVAILABLE'
DRIVER_STATUSES = (
    DRIVER_STATUS_AVAILABLE,
    DRIVER_STATUS_ENROUTE,
    DRIVER_STATUS_UNAVAILABLE,
)

DELIVERY_STATUS_NEW = 'NEW'
DELIVERY_STATUS_ENROUTE = 'ENROUTE'
DELIVERY_STATUS_CANCELED = 'CANCELED'
DELIVERY_STATUS_DELIVERED = 'DELIVERED'
DELIVERY_STATUSES = (
    DELIVERY_STATUS_NEW,
    DELIVERY_STATUS_ENROUTE,
    DELIVERY_STATUS_CANCELED,
    DELIVERY_STATUS_DELIVERED,
)